name: Build and Push Dev Image
# Workflow name

on:
  push:
    branches:
      - dev
# Trigger on push to the 'dev' branch

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    # Runner OS

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Image
        run: docker image build -t bahamelki/simplewebdev -f Dockerfile.dev .

      - name: Push Image
        run: docker image push bahamelki/simplewebdev
